compatibility_date = "2022-05-22"
main = "src/index.ts"

workers_dev = true

[site]
bucket = "../remix-app/public"

[env.dev]
vars = { ACCESS_KEY = "secret", DISSALLOWED_DOMAINS = "domain.one domain.two domain.three", APP_URL = "sho.rt" }

kv_namespaces = [{ binding = "URLS", preview_id = "<preview_id>", id = "<id>" }]
