type = 'javascript'
compatibility_date = '2022-05-22'
main = 'src/index.ts'
name = 'remix-app'
account_id = '5c8031e391b1a8e8666e99701ba97e6d'

kv_namespaces = [
  { binding = "URLS", id = "d5bb2adc69b0404890c9fe1171e26623" }
]

[site]

bucket = '../remix-app/public'